apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-catalog
  namespace: fastfood
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-catalog
  template:
    metadata:
      labels:
        app: postgres-catalog
    spec:
      containers:
        - name: postgres-catalog
          image: postgres:17.5-alpine3.21
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: fiap-ms-catalog
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: catalog-secret
                  key: SPRING_DATASOURCE_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: catalog-secret
                  key: SPRING_DATASOURCE_PASSWORD
          volumeMounts:
            - name: postgres-storage-catalog
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage-catalog
          persistentVolumeClaim:
            claimName: postgres-catalog-pvc
