apiVersion: v1
kind: Secret
metadata:
    name: catalog-secret
    namespace: fastfood
type: Opaque
data:
    SPRING_DATASOURCE_USERNAME: ZmlhcHRjLWNhdGFsb2c=  # base64 de "fiaptc-catalog"
    SPRING_DATASOURCE_PASSWORD: ZmlhcHRjMTIzNA==      # base64 de "fiaptc1234"
