apiVersion: v1
kind: Secret
metadata:
    name: catalog-secret
    namespace: fastfood
type: Opaque
data:
    SPRING_DATASOURCE_USERNAME: ZmlhcHRjLXByb2R1Y3Rz  # base64 de "fiaptc-products"
    SPRING_DATASOURCE_PASSWORD: ZmlhcHRjMTIzNA==      # base64 de "fiaptc1234"
