apiVersion: v1
kind: Secret
metadata:
    name: catalog-secret
    namespace: fastfood
type: Opaque
data:
    SPRING_DATASOURCE_USERNAME: ZmlhcA==   # fiap
    SPRING_DATASOURCE_PASSWORD: UDRzc3cwcmQxMjM=      # P4ssw0rd123
